### PR TITLE
Doc/log/action improvements

### PR DESCRIPTION
**Pull request by pdiakumis**
Just adding some small doc notes and cleaning the log messages a bit.
Also cleaned up/updated GitHub Action workflow.

See commit messages for details.

### CODE REVIEW

**Comment by pdiakumis** [comment]
I'm also getting the following warning when using the `--estimate_tmb` option:

```
Warning message:
`gather_()` was deprecated in tidyr 1.2.0.
Please use `gather()` instead.
```

I've seen it before and I think it was from a dependency of a dependency, will try and remember.

**Comment by sigven** [comment]
> I'm also getting the following warning when using the `--estimate_tmb` option:
> 
> ```
> Warning message:
> `gather_()` was deprecated in tidyr 1.2.0.
> Please use `gather()` instead.
> ```
> 
> I've seen it before and I think it was from a dependency of a dependency, will try and remember.

Yeah, I've noticed that one too, and I think you're right (dep of a dep)

**Comment by pdiakumis** [comment]
Adding it here too - that warning is from plotly, see <https://github.com/plotly/plotly.R/pull/2125>.
And the backtrace:

```
Backtrace:
 1. plotly::ggplotly(tmb_plot_site)
 2. plotly:::ggplotly.ggplot(tmb_plot_site)
 3. plotly::gg2list(...)
 4. plotly:::layers2traces(data, prestats_data, layout, plot)
 6. plotly:::to_basic.GeomHline(...)
 7. tidyr::gather_(...)
```

**Comment by pdiakumis** [comment]
Just cleaned up/simplified a couple of the dicts, ready for review now.

**Review by sigven — APPROVED** [review]
Looks good, Peter. Thanks a lot for doing these clean-ups.. :-)

**Pull request merged**
