### PR TITLE
No-docker option

### PR DESCRIPTION
**Pull request by vladsaveliev**
Hi Sigve,

Following up https://github.com/sigven/pcgr/issues/35, prepared the pull request with the changes to run with `--no-docker`. Cleaned it up a bit after the initial changes, and going with a single `pcgr.py` script because all the differences are quite simple:

https://github.com/sigven/pcgr/compare/master...vladsaveliev:master?w=1#files_bucket
(using `?w=1` in URL to ignore the whitespaces for a cleaner diff :)

Looks like a lot of changes, but they all are basically just the following:
- new `install_no_docker` folder that has stuff for installation (install.sh script, conda env file, and readme),
- in executable scripts `pcgr.py`, `pcgr.R`, `pcgr_validate_input.py`, replaced the hardcoded docker-related paths with variables,
- in `pcgr.py`, added a big if-else: `if docker_image_version: <initialize paths for docker> else: <initialize paths for local runs>`
- added .gitignore and remove `.pyc` from git :)

I tested the fresh installation on two Linux machines: Red Hat 4.8.5 and Red Hat 5.3.1. Also tried to make it work on MacOS, but ran into an issue with VEP via conda: https://github.com/bioconda/bioconda-recipes/pull/8801 Will pursue that and make it work for MacOS too :)

Happy to make any changes that you suggest!

Vlad

### CODE REVIEW

**Comment by sigven** [comment]
Hi Vlad, This looks great! Any updates on having it working for MacOS?

**Comment by sigven** [comment]
Hi Vlad,

I am adding the [VEP LofTee plugin](https://github.com/konradjk/loftee) in the next release, which I believe is a useful add-on functionality. To make it work inside Docker, I basically made an archive of the LofTee code repo (with some minor custom changes and removal of warnings), and placed them in the `ensembl-vep/modules`directory. Would you care to try including and testing it for the `install_no_docker`setup?

regards,
Sigve

**Comment by vladsaveliev** [comment]
Hey Sigve,

Happy to try it. How do you install it: with `vep_install --PLUGINS LoF`, or you have to clone the repo first? 

I you commit an updated Dockerfile, I can add the plugin into the installer script and run tests.

Vlad

**Comment by sigven** [comment]
Hi Vlad,
Sorry for the delay here (vacation mode.). I'll commit an updated Docker next week for you to test.

best,
Sigve

**Pull request merged**
